---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: concourse/buildroot
    tag: curl

run:
  path: bash
  args:
  - -ec
  - |
    set -e
    echo "Trying to curl $CONNECT_TO_URL with parameters [$EXTRA_COMMAND_PARAMETERS]"
    set -x
    curl "$CONNECT_TO_URL" $EXTRA_COMMAND_PARAMETERS

params:
  CONNECT_TO_URL:
  EXTRA_COMMAND_PARAMETERS:
