---
#
# PCF Documentation: https://docs.pivotal.io/pivotalcf/security/pcf-infrastructure/api-cert-rotation.html
#
resources:
- name: pcf-pipelines-utils
  type: git
  source:
    uri: https://github.com/pivotalservices/concourse-pipeline-samples.git

jobs:
- name: Rotate-Non-Configurable-Certificates
  plan:
  - get: pcf-pipelines-utils
  - task: rotate-non-configurable-certificates
    file: pcf-pipelines-utils/tasks/pcf/certificates/regenerate-internal-certificates/task.yml
    params:
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain}}
      OPSMAN_USERNAME: {{opsman_admin_username}}
      OPSMAN_PASSWORD: {{opsman_admin_password}}
      OPSMAN_CLIENT_ID: {{opsman_client_id}}
      OPSMAN_CLIENT_SECRET: {{opsman_client_secret}}
  - task: apply-changes
    file: pcf-pipelines-utils/tasks/pcf/apply-changes/task.yml
    params:
      OPSMAN_CLIENT_ID: {{opsman_client_id}}
      OPSMAN_CLIENT_SECRET: {{opsman_client_secret}}
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain}}
      OPSMAN_PASSWORD: {{opsman_admin_password}}
      OPSMAN_USERNAME: {{opsman_admin_username}}
